[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stakefeed = "2Y48nF8ne9o1pVJoTcvv6EtYDM8TEwWszUyaqzSZmz8D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec tsx tests/stakefeed.ts"

[hooks]
